version: 2
jobs:
  build:
    working_directory: ~/mtransit
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      TERM: xterm-256color
      JVM_OPTS: -Xmx3200m
    steps:
      - run:
          name: Update SDK
          command: echo y | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3" "platform-tools" "platforms;android-28"
      - checkout
      - run:
          name: Checkout commons submodule
          command: git submodule update --init --recursive commons
      - run:
          name: Checkout parser submodule
          command: git submodule update --init --recursive parser
      - run:
          name: Checkout agency-parser submodule
          command: git submodule update --init --recursive agency-parser
      - run:
          name: Checkout commons-android submodule
          command: git submodule update --init --recursive commons-android
      - run:
          name: Checkout app-android submodule
          command: git submodule update --init --recursive app-android
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "commons-android/build.gradle" }}-{{ checksum "commons-android/commons-android.gradle" }}-{{ checksum "parser/build.gradle" }}-{{ checksum "agency-parser/build.gradle" }}-{{ checksum "app-android/build.gradle" }}
      - run:
          name: gradlew permissions
          command: sudo chmod +x gradlew
      - run:
          name: build.sh permissions
          command: sudo chmod +x build.sh
      - run:
          name: agency-parser/list_change.sh permissions
          command: sudo chmod +x agency-parser/list_change.sh
      - run:
          name: app-android/build.sh permissions
          command: sudo chmod +x app-android/build.sh
      - run:
          name: app-android/keys_*.sh permissions
          command: sudo chmod +x app-android/keys_*.sh
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --console=plain
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "commons-android/build.gradle" }}-{{ checksum "commons-android/commons-android.gradle" }}-{{ checksum "parser/build.gradle" }}-{{ checksum "agency-parser/build.gradle" }}-{{ checksum "app-android/build.gradle" }}
      - run:
          name: Build
          command: ./build.sh
      - store_artifacts:
          path: app-android/build/reports
          destination: reports
      - store_artifacts:
          path: app-android/build/outputs/apk
          destination: apks
      - store_artifacts:
          path: commons-android/build/reports
          destination: commons-android-reports
      - store_test_results:
          path: app-android/build/test-results
      - store_test_results:
          path: commons-android/build/test-results
